---
title: "Introducción"
numbered: true
---

Motivación, preguntas de investigación, Objetivo general y específicos, contribución esperada, estructura del documento.

El suicidio representa uno de los desafíos de salud mas críticos y complejos de la actualidad. Caracterizado por su multifactorialidad, es un fenómeno que involucra aspectos biológicos, psicológicos, sociales y culturales. La comprensión de sus causas y la implementación de estrategias efectivas de prevención son esenciales para reducir su incidencia y mitigar sus consecuencias. Sin embargo, a pesar de los esfuerzos realizados en el ámbito de la salud pública, el suicidio sigue siendo un problema persistente y alarmante a nivel global. 

En este marco, el presente reporte abierto tendrá como objetivo transparentar una investigación titulada [*El fenómeno de la ideación suicida en Chile*](-@lewinfenomeno2026), llevada a cabo por estudiantes de tercer año de Sociología de la Universidad de Chile. El trabajo tiene como propósito identificar las condiciones sociales que podrían llegar a ser factotres que incidan en la ideación suicida en Chile, considerando una población muestral de personas mayores a 30 años. Por tanto, la pregunta de investigación es: ¿Como afectan las condiciones sociales y psicológicas en los individuos en los niveles de ideación suicida?.   

Nos parece un tema de gran relevancia, puesto que considera en su modelo variables de carácter tanto estructural como psicológica, a diferencia de otros estudios cuyo énfasis recae en lo psicológico.  Por tanto, se espera que el trabajo contribuya a la comprensión de la causalidad entre los factores estructurales como antecedentes de ideación suicida en la población estudiada.

En primer lugar, se presentarán los antecedentes teóricos y empíricos del fenómeno del suicidio con el fin de contextualizar la investigación. Posteriormente, se darán a conocer las hipotésis de investigación y los resultados esperados. Seguido de esto, los métodos utilizados para el tratamiento y flujo de trabajo en los datos con el fin de preparar la base para el análisis de regresión lineal múltiple. Finalmente, se presentarán los resultados obtenidos y se discutirá su relevancia en el contexto de la investigación y proyecciones futuras.  








