---
title: "Antecedentes"
---
*Nota metodológica: Este apartado teórico e institucional se basa y rescata pasajes de la investigación inédita de @lewinfenomeno2026, la cual es tomada como el manuscrito base para la elaboración de este reporte abierto.

## El suicidio como fenómeno multidimensional y estructural
"El suicidio representa uno de los desafíos de salud pública más críticos y complejos de la actualidad" [@lewinfenomeno2026]. Si bien suele abordarse desde una perspectiva individual, los datos globales de la Organización Mundial de la Salud [@omssuicidio2025] exponen que el 73% de los suicidios ocurren en países de ingresos bajos y medianos, evidenciando una clara contradicción socioeconómica. Desde la sociología clásica Durkheim plantea que "el grado de cohesión social de una sociedad está en relación inversa a la tasa social de suicidios" [@lewinfenomeno2026]. Por ende, cuando los lazos colectivos o las normas que regulan las expectativas se fracturan, los individuos quedan expuestos a un mayor riesgo autolítico.
Siguiendo el diseño original de @lewinfenomeno2026, este estudio restringe su foco al análisis de la *ideación suicida* en la población chilena de 30 años o más. La ideación suicida es un marcador de vulnerabilidad caracterizado por pensamientos de quitarse la vida con variados niveles de planificación [@rizvisuicidal2024; @canonideacion2018], constituyendo el principal predictor de los intentos de suicidio y los suicidios consumados. 

## Sustento de los factores explicativos del modelo
Para modelar estadísticamente la propensión a la ideación suicida, se seleccionaron cinco variables predictoras que articualn dimensiones clínicas, psicosociales y materiales [@lewinfenomeno2026]. 
En primer lugar, desde la dimensión clínico-psicológica, se incorpora la *depresión*. A nivel nacional, @martinezideación2026 dmeuestra que esta es la variable más estrechamente relacionada con la ideación suicida a lo largo del ciclo vital adulto. 
En segundo lugar, se incluye la *sensación de fracaso*, variable que operacionaliza la frutración ante la brecha entre las expectativas de éxito socioculturales y las oportunidades reales para alcanzarlas. Este fenómeno es conceptualizado por @besorasemantica2023 como *suicidio endorreferencial*, donde la autopercepción de fracaso basada en metas sociales actúa como detonante de la desesperanza. 
En tercer lugar, el modelo integra factores socioeconómicos de *despido laboral* e *insatisfacción con los ingresos*. La pérdida del empleo opera como un evento vital estresante que eleva directamente la sintomatología depresiva y el riesgo autolítico [@wloskodespidos2016], mientras que la insatisfacción con los ingresos permite medir la vulnerabilidad financiera subjetiva ante la incapacidad de solventar dignamente las necesidades materiales básicas [@lópezfactores2025]. Finalmente, el *estado civil* se incorpora bajo la premisa de que la soltería o separación representan una pérdida de soporte relacional primario que incrementa la vulnerabilidad del sujeto [duartesuicidio2006]. 