---
title: "Resultados"
---

El modelo de regresión completo es estadísticamente significativo (p < .001) y puede explicar alrededor del 28% del fenómeno (R-cuadrado ajustado = .280). El valor del intercepto (1.53) refiere al valor del índice de ideación suicida con todas las variables controladas en valor 0, es decir, el valor del intercepto representa a una persona que está satisfecha con sus ingresos, no fue despedida de su trabajo, no presenta sensación de fracaso, no sufre de depresión y su estado civil en pareja, presenta un puntaje del índice de ideación suicida de 1.53, lo cual, según los criterios establecidos, es un puntaje bajo; esto se puede afirmar con más de un 99.9% de confianza (p < .001). 

La primera variable, depresión, presenta una significación estadística del 99.9% (P < .001), pudiendo rechazar la hipótesis nula (H1 ≠ 0); además, presenta una dirección positiva (b1 = 1.90) y un tamaño de efecto medio-bajo (STD (b) = 0.24) según los criterios de Cohen, controlando por todas las demás variables. De esto se desprende que las personas con depresión aumentan su puntaje en el índice de ideación suicida en relación al valor del intercepto en 1.90 puntos y, al contrario, las personas que no presentan depresión disminuyen su puntaje en el índice de ideación suicida. Por ende, para este caso se cumple la hipótesis formulada desde el marco teórico, donde se establece que existe una relación positiva entre la depresión y el suicidio.

La segunda variable, estado civil, no es estadísticamente significativa (p  > .05), no pudiendo rechazar la hipótesis nula (H2 = 0), la variable presenta una dirección negativa (b1 = -0.13) y un tamaño de efecto bajo (STD (b) = -0.025) según los criterios de Cohen, controlando por todas las demás variables. De esto se desprende que las personas que se encuentran sin pareja disminuyen su puntaje en el índice de ideación suicida en relación al valor del intercepto en 0.13 puntos y, al contrario, las personas que se encuentran en pareja aumentan su puntaje en el índice de ideación suicida, aunque, como se mencionó anteriormente, esto no se puede afirmar a nivel poblacional. Aun así, existe una incoherencia entre los datos arrojados por el modelo y la hipótesis planteada, donde se expresa que en ausencia de relaciones de pareja debieran aumentar los niveles de ideación suicida, en este caso ocurre todo lo contrario. 

La tercera variable, sensación de fracaso, presenta una significación estadística del 99.9% (P < .001), pudiendo rechazar la hipótesis nula (H4 ≠ 0); además, presenta una dirección positiva (b1 = 2.33) y un tamaño de efecto mediano (STD (b) = 0.37) según los criterios de Cohen controlando por todas las demás variables.  De esto se desprende que las personas con sensación de fracaso aumentan su puntaje en el índice de ideación suicida en relación al valor del intercepto en 2.33 puntos y, al contrario, las personas que no experimentan sensación de fracaso disminuyen su puntaje en el índice de ideación suicida. Por ende, para este caso se cumple la hipótesis formulada desde el marco teórico, donde se establece que la sensación de fracaso como experiencia representa el quiebre de las expectativas del individuo en diversos ámbitos de la vida social, expectativas que a su vez son determinadas por la sociedad a través de sus instituciones, las cuales, al ser incumplidas, podrían empujar a las personas a caer en ideaciones suicidas o incluso consumar suicidio endoreferencial, un tipo de suicidio motivado por propósitos internos dentro de los cuales está el fracaso de las expectativas individuales socialmente fundadas. 

La cuarta variable, despido, no es estadísticamente significativa (p > .05), no pudiendo rechazar la hipótesis nula (H3 = 0); además, presenta una dirección positiva (b1 = 0.26) y un tamaño de efecto bajo (STD (b) = 0.027) según los criterios de Cohen, controlando por todas las demás variables. De esto se desprende que las personas despedidas aumentan su puntaje de ideación suicida 0.26 puntos y, al contrario, una persona que no se encuentra despedida disminuye su puntaje en el índice de ideación suicida, aunque, como se mencionó anteriormente, esto no se puede afirmar a nivel poblacional debido a que no se cumple con la significancia estadística. A pesar de existir coherencia entre los datos del modelo y la hipótesis teórica, no existe evidencia empírica para aceptar que el despido genera mayores niveles de ideación suicida.

La quinta y última variable, insatisfacción con ingreso, presenta una significación estadística del 99.9% (P < .001), pudiendo rechazar la hipótesis nula (H5 ≠ 0); además, presenta una dirección positiva (b1 = 0.59) y un tamaño de efecto bajo (STD (b) = 0.11) según los criterios de Cohen controlando por todas las demás variables. De esto se desprende que las personas que presentan insatisfacción con sus ingresos aumentan su puntaje en el índice de ideación suicida en relación al valor del intercepto en 0.59 puntos y, al contrario, una persona que presenta satisfacción con sus ingresos disminuye su puntaje en el índice de ideación suicida. Por ende, para este caso se cumple la hipótesis formulada, donde se establece que existe una conexión entre el grado de insatisfacción subjetiva con los ingresos asociado a la posibilidad de solventar sus necesidades vitales, reflejando así cómoc la insatisfacción, debido a la precariedad económica producida por la cantidad de ingresos que percibe la persona, puede empujar a caer en pensamientos de ideación suicida. 

Dentro de las limitaciones del modelo, se encuentra que no se hizo filtrado por sexo, por lo que no se puede afirmar que los resultados sean iguales para hombres, mujeres y disidencias en los niveles de ideación suicida. Se hace necesario agregar este filtrado dada las distinciones en términos de experiencia, necesidades y problemáticas a nivel estructural que presentan los distintos géneros, lo cual podría afectar en el índice creado. Otra limitante encontrada tiene que ver con la temporalidad de las variables explicativas/independientes. Por ejemplo, no es lo mismo que una persona haya sido despedida hace 10 años a que haya sido despedida hace 1 año, ya que la experiencia de haber sido despedido puede tener un efecto distinto en el tiempo, o, una persona que haya sido diagnosticada con depresión hace 10 años a que haya sido diagnosticada hace 1 año, ya que la experiencia de haber sido diagnosticado puede tener un efecto distinto en el tiempo. Por lo tanto, se recomienda que en futuras investigaciones se considere la temporalidad para obtener resultados más precisos y confiables.

Sim embargo, los resultados del modelo señalan que efectivamente los factores psicologicos tienen mas peso en la ideación suicida que los factores estructurales, lo cual es coherente con la literatura existente, lo que se considera un buen aporte puesto que esta bajo la misma línea que sugiere la investigación científica. Esto sugiere que, aunque las condiciones sociales y económicas son importantes, los factores psicológicos como la depresión, sensación de fracaso e insatisfaccion con ingresos tienen un impacto más directo y significativo en la ideación suicida.  A pesar de ello, no se descarta la influencia de los factores estructurales, como dinamicas familiares, instituciones académicas, económicas y políticas públicas impartidas por el Estado, que podrían afectar directa o indirectamente la experiencia de los individuos. 

