---
title: "Conclusiones"
---
## Síntesis y proyecciones futuras:

En síntesis, este trabajo logró con satisfacción identificar que los factores psicológicos tienen un peso significativamente mayor que los factores estructurales en la ideación suicida, a pesar de haber sido partidarios de la hipótesis de que los factores estructurales tendrían un peso mayor o ser estadísticamente significativos en base a la evidencia disponible. Esto se puede explicar por la naturaleza del fenómeno, ya que la ideación suicida es un fenómeno complejo y multidimensional, donde los factores psicológicos tienen un impacto más directo y significativo en la ideación suicida. Además, no se descarta la influencia de otras variables de carácter estructural que podrían estar afectando la ideación suicida y que no fueron incluidas en el modelo. 

Se proyecta que en futuras investigaciones, se continúe investigando la relación y la dinámica entre estos dos factores con datos actualizados. Como bien se mencionó, se utilizaron datos de la ola 6 del Estudio Longitudinal Social de Chile (ELSOC), levantada en el año 2022, por lo que se recomienda que en futuras investigaciones se utilicen datos más recientes para obtener resultados más precisos y confiables. Además, se tendrá en consideracion la utilización de otros modelos estadísticos, como la regresión logística binaria, para poder analizar la probabilidad de que una persona presente ideación suicida, en lugar de analizar el nivel de ideación suicida. De otro modo, no se descarta, además de los modelos de regresión, la utilización de análisis multinivel con el fin de investigar el comportamiento del fenómeno a través del tiempo. Lo anterior responde a que la base de datos ELSOC es la única encuesta longitudinal en Chile, lo que métodologicamente presenta una ventaja mucho mayor que las bases de datos transversales, desde el punto de vista análitico/temporal. 

## Alcances y límites del proyecto abierto

En la realización de este proyecto abierto, mediante las informaciones obtenidas a partir de la base de datos del Estudio Longitudinal Social de Chile (ELSOC) utilizado en la investigación sobre el Fenómeno de la ideación suicida en Chile, se identifica la posibilidad de transparencia y reproducibilidad puesto que se tiene un acceso completo a los datos, fuentes y códigos utilizados. No obstante, cabe recalcar que esto ocurre ya que se está utilizando una investigación inédita, realizada grupalmente por estudiantes de Sociología de la Universidad de Chile, dentro de los cuales se encuentra uno de los autores de este trabajo, por lo que se tiene acceso a la información de manera directa. Se destaca esto debido que no siempre se logra un acceso directo y simple a los datos y códigos utilizados en investigaciones, lo que limita justamente la ciencia abierta.  

En sumatoria, se identidica como una limitación al estudio, que aquel no incluye un filtrado por género, lo que limita la generalización de los resultados a diferentes poblaciones.



